In [10]:
import os 
import pandas as pd

# Questionnaires

In [ ]:
q = pd.read_csv("data/preprocessed/record_20260929_141938_questionnaire.csv")
q_cols = ["session_id","language","administration","questionnaire_id","question","response"]
q[q_cols]

,session_id,language,administration,questionnaire_id,question,response
0,dfb95fe0_2026-09-29_09-14-28,FR,1,language,language,FR
1,dfb95fe0_2026-09-29_09-14-28,FR,1,demographics,status,thésard
2,dfb95fe0_2026-09-29_09-14-28,FR,1,demographics,education,bac + 6
3,dfb95fe0_2026-09-29_09-14-28,FR,1,demographics,age,2
4,dfb95fe0_2026-09-29_09-14-28,FR,1,EES,curieux / curieuse,un tout petit peu
...,...,...,...,...,...,...
139,dfb95fe0_2026-09-29_09-14-28,FR,1,JrMAI,Je vérifie de temps en temps que je vais bien ...,Souvent
140,dfb95fe0_2026-09-29_09-14-28,FR,1,JrMAI,Je détermine ce que je dois accomplir avant de...,Parfois
141,dfb95fe0_2026-09-29_09-14-28,FR,1,JrMAI,Je réfléchis à ce que je dois apprendre avant ...,Rarement
142,dfb95fe0_2026-09-29_09-14-28,FR,1,JrMAI,Je sais quand je comprends quelque chose.,Parfois
143,dfb95fe0_2026-09-29_09-14-28,FR,1,JrMAI,Je sais ce que le professeur attend de moi.,Rarement

# Exploration

In [22]:
N_COLUMNS, N_ROWS = 7, 7

In [23]:
e = pd.read_csv("data/preprocessed/record_20260929_141938_exploration.csv")
e["action"] = e["position_rowID"]*N_COLUMNS + e["position_columnID"]

In [41]:
restricted_e = e[~e["only_select"]][["session_id","trial","action","predicted_value","actual_value"]]
restricted_e

                      session_id  trial  action  predicted_value  actual_value
4   dfb95fe0_2026-09-29_09-14-28      0      26                9             8
6   dfb95fe0_2026-09-29_09-14-28      1      26                5             6
8   dfb95fe0_2026-09-29_09-14-28      2      26                5             9
10  dfb95fe0_2026-09-29_09-14-28      3      27                6             7
12  dfb95fe0_2026-09-29_09-14-28      4      26                9             9
14  dfb95fe0_2026-09-29_09-14-28      5      25                9             5
16  dfb95fe0_2026-09-29_09-14-28      6      19                9             7
18  dfb95fe0_2026-09-29_09-14-28      7       8                5            10
20  dfb95fe0_2026-09-29_09-14-28      8      29                9             5
22  dfb95fe0_2026-09-29_09-14-28      9      30                9            10